"""Build the local book reader from chapters/*.md + book.json.

Markdown in, one HTML reader out. Each chapter may carry desk front matter
(job, happens, notes) so the top-down plan sits on the page.

  python scripts/build.py
"""
from __future__ import annotations

import html
import json
import re
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CHAPTERS = ROOT / "chapters"
OUT = ROOT / "index.html"
META = ROOT / "book.json"


def volume_of(path: Path) -> tuple[int, str]:
    parts = {p.lower() for p in path.parts}
    if "book-1-shadow" in parts or "book-1" in parts:
        return 1, "Shadow"
    if "book-2-green" in parts or "book-2" in parts:
        return 2, "Green"
    if "book-3-crow" in parts or "book-3" in parts:
        return 3, "Crow"
    return 1, "Shadow"


def parse_front_matter(raw: str) -> tuple[dict, str]:
    desk = {
        "status": "draft",
        "room": "",
        "job": "",
        "happens": [],
        "notes": "",
    }
    if not raw.startswith("---"):
        return desk, raw
    rest = raw[3:].lstrip("\n")
    end = rest.find("\n---")
    if end < 0:
        return desk, raw
    block = rest[:end]
    body = rest[end + 4 :].lstrip("\n")

    key = None
    notes: list[str] = []
    for line in block.splitlines():
        if line.startswith("status:"):
            key = "status"
            desk["status"] = line.split(":", 1)[1].strip()
        elif line.startswith("room:"):
            key = "room"
            desk["room"] = line.split(":", 1)[1].strip()
        elif line.startswith("job:"):
            key = "job"
            desk["job"] = line.split(":", 1)[1].strip()
        elif line.startswith("happens:"):
            key = "happens"
        elif line.startswith("notes:"):
            key = "notes"
            tail = line.split(":", 1)[1].strip()
            if tail and tail not in ("|", ">"):
                notes.append(tail)
        elif key == "happens" and line.strip().startswith("- "):
            desk["happens"].append(line.strip()[2:].strip())
        elif key == "job" and (line.startswith("  ") or line.startswith(" ")):
            desk["job"] = (desk["job"] + " " + line.strip()).strip()
        elif key == "notes":
            notes.append(line[2:] if line.startswith("  ") else line)
    desk["notes"] = "\n".join(notes).strip()
    return desk, body


def parse_chapter(path: Path) -> dict:
    raw = path.read_text(encoding="utf-8")
    desk, raw = parse_front_matter(raw)
    lines = raw.splitlines()
    num = 0
    m = re.search(r"ch-(\d+)", path.name)
    if m:
        num = int(m.group(1))
    title = path.stem
    kicker = f"Chapter {num}"
    i = 0
    if lines and lines[0].startswith("# "):
        kicker = lines[0][2:].strip()
        i = 1
    if i < len(lines) and lines[i].startswith("## "):
        title = lines[i][3:].strip()
        i += 1
    while i < len(lines) and not lines[i].strip():
        i += 1
    body = "\n".join(lines[i:]).strip()
    vol, vol_name = volume_of(path)
    return {
        "num": num,
        "title": title,
        "kicker": kicker,
        "body": body,
        "path": path.name,
        "volume": vol,
        "volume_name": vol_name,
        "words": len(body.split()),
        "desk": desk,
    }


def chapter_files() -> list[Path]:
    nested = list(CHAPTERS.rglob("ch-*.md"))
    files = nested if nested else list(CHAPTERS.glob("ch-*.md"))
    return sorted(files, key=lambda p: (volume_of(p)[0], parse_chapter(p)["num"]))


def write_wordcount(book: dict, chapters: list[dict], total_words: int) -> None:
    length = book.get("length") or {}
    books = {b["number"]: b for b in length.get("books", [])}
    by_vol: dict[int, int] = {}
    for c in chapters:
        by_vol[c["volume"]] = by_vol.get(c["volume"], 0) + c["words"]
    lines = [
        "# Wordcount",
        "",
        "Generated by `python scripts/build.py`. Law: [LENGTH.md](LENGTH.md).",
        "",
        "Do not write toward the centre line. Write the locked rooms.",
        "",
        f"Series so far: **{total_words:,}** / 400–450k",
        "",
        "| Book | Words | Centre | Band | Floor |",
        "|------|------:|-------:|------|------:|",
    ]
    for n, name in ((1, "Shadow"), (2, "Green"), (3, "Crow")):
        meta = books.get(n, {})
        w = by_vol.get(n, 0)
        centre = meta.get("centre", 0)
        band = meta.get("band", [0, 0])
        band_s = f"{band[0]//1000}–{band[1]//1000}k" if band[1] else "—"
        centre_s = f"{centre//1000}k" if centre else "—"
        lines.append(
            f"| {n} · {name} | {w:,} | {centre_s} | {band_s} | 110k |"
        )
    lines += [
        "",
        "## Chapters",
        "",
        "| Vol | # | Title | Job | Status | Words |",
        "|-----|---|-------|-----|--------|------:|",
    ]
    for c in chapters:
        job = (c["desk"].get("job") or "").replace("|", "/")
        if len(job) > 80:
            job = job[:77] + "…"
        lines.append(
            f"| {c['volume']} | {c['num']} | {c['title']} | {job} | {c['desk'].get('status', '')} | {c['words']:,} |"
        )
    (ROOT / "docs" / "WORDCOUNT.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def md_lite_to_html(text: str) -> str:
    fences: list[str] = []

    def save_fence(m: re.Match) -> str:
        fences.append(m.group(1))
        return f"\x00FENCE{len(fences) - 1}\x00"

    text = re.sub(r"```[^\n]*\n(.*?)```", save_fence, text, flags=re.DOTALL)
    parts = re.split(r"\n\s*\n", text)
    out: list[str] = []
    for part in parts:
        p = part.strip()
        if not p:
            continue
        if p.strip() == "---":
            out.append("<hr>")
            continue
        if p.startswith("#"):
            p = re.sub(r"^#+\s*", "", p)
        esc = html.escape(p)
        esc = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", esc)
        esc = re.sub(r"(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)", r"<em>\1</em>", esc)
        esc = re.sub(r"`([^`]+)`", r"<code>\1</code>", esc)
        esc = esc.replace("\n", "<br>\n")
        for i, code in enumerate(fences):
            esc = esc.replace(
                f"\x00FENCE{i}\x00",
                f"<pre><code>{html.escape(code.rstrip())}</code></pre>",
            )
        if esc.startswith("<pre>"):
            out.append(esc)
        else:
            out.append(f"<p>{esc}</p>")
    return "\n".join(out)


def desk_html(c: dict) -> str:
    d = c["desk"]
    if not d.get("job") and not d.get("happens") and not d.get("notes"):
        return (
            '<aside class="desk">'
            "<p class=\"desk-empty\">No desk card yet. Add YAML front matter "
            "(job, happens, notes) at the top of the chapter file.</p>"
            "</aside>"
        )
    happens = "".join(f"<li>{html.escape(h)}</li>" for h in d.get("happens") or [])
    happens_h = (
        f'<h3 class="desk-k">What happens</h3><ul class="desk-happens">{happens}</ul>'
        if happens
        else ""
    )
    notes_h = ""
    if d.get("notes"):
        notes_h = (
            '<h3 class="desk-k">Notes</h3>'
            f'<div class="desk-notes">{md_lite_to_html(d["notes"])}</div>'
        )
    room = html.escape(d["room"]) if d.get("room") else ""
    room_html = f'<span class="desk-room">{room}</span>' if room else ""
    status = html.escape(d.get("status") or "draft")
    return f"""<aside class="desk" aria-label="Desk card">
      <div class="desk-top">
        <span class="desk-status s-{html.escape(d.get('status') or 'draft')}">{status}</span>
        {room_html}
      </div>
      <h3 class="desk-k">Job</h3>
      <p class="desk-job">{html.escape(d.get("job") or "")}</p>
      {happens_h}
      {notes_h}
    </aside>"""


def spine_html(chapters: list[dict]) -> str:
    rows = []
    for c in chapters:
        job = html.escape(c["desk"].get("job") or "—")
        st = html.escape(c["desk"].get("status") or "draft")
        cid = f"ch-{c['num']:02d}"
        rows.append(
            "<tr>"
            f'<td class="sp-n">{c["num"]}</td>'
            f'<td class="sp-t"><a href="#{cid}">{html.escape(c["title"])}</a></td>'
            f'<td class="sp-j">{job}</td>'
            f'<td class="sp-s">{st}</td>'
            f'<td class="sp-w">{c["words"]:,}</td>'
            "</tr>"
        )
    return f"""<section class="spine" id="spine" aria-label="Chapter spine">
      <h2>Spine</h2>
      <p class="spine-lead">Top-down. The job of each chapter without the prose. Click through to the room.</p>
      <div class="spine-wrap">
      <table>
        <thead>
          <tr><th>#</th><th>Title</th><th>Job</th><th>Status</th><th>Words</th></tr>
        </thead>
        <tbody>
          {"".join(rows)}
        </tbody>
      </table>
      </div>
    </section>"""


def build() -> Path:
    book = json.loads(META.read_text(encoding="utf-8"))
    files = chapter_files()
    if not files:
        raise SystemExit(f"No chapters in {CHAPTERS}")
    chapters = [parse_chapter(p) for p in files]
    total_words = sum(c["words"] for c in chapters)
    write_wordcount(book, chapters, total_words)
    shadow = sum(c["words"] for c in chapters if c["volume"] == 1)
    target = ((book.get("length") or {}).get("books") or [{}])[0].get("centre", 125000)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    title = book.get("title") or "Untitled"
    author = book.get("author") or ""
    subtitle = book.get("subtitle") or ""
    epigraph = book.get("epigraph") or ""
    badge = book.get("badge") or "draft"
    robots = book.get("robots") or "noindex, nofollow, noarchive"
    status = book.get("status") or "draft"
    hero_line = subtitle or epigraph or author

    nav: list[str] = []
    sections: list[str] = []
    for c in chapters:
        cid = f"ch-{c['num']:02d}"
        nav.append(
            f'<a class="nav-item" href="#{cid}">'
            f'<span class="n">{c["num"]}</span>'
            f'<span class="t">{html.escape(c["title"])}</span></a>'
        )
        body_html = md_lite_to_html(c["body"])
        w = c["words"]
        sections.append(
            f'<article class="chapter" id="{cid}">'
            f'<header class="ch-head">'
            f'<p class="kicker">{html.escape(c["kicker"])}</p>'
            f'<h2>{html.escape(c["title"])}</h2>'
            f'<p class="meta">{w:,} words · {html.escape(c["desk"].get("status") or "draft")}</p>'
            f"</header>"
            f"{desk_html(c)}"
            f'<div class="body">{body_html}</div>'
            f"</article>"
        )

    epigraph_html = ""
    if epigraph:
        epigraph_html = f'<div class="epigraph">{html.escape(epigraph)}</div>'

    sub_html = html.escape(author)
    if subtitle:
        sub_html = html.escape(subtitle)

    page = f"""<!DOCTYPE html>
<html lang="en-GB">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{html.escape(title)}</title>
  <meta name="description" content="{html.escape(title)}{(' — ' + author) if author else ''}">
  <meta name="robots" content="{html.escape(robots)}">
  <meta name="theme-color" content="#12110f">
  <link rel="stylesheet" href="reader.css">
  <script defer src="reader.js"></script>
</head>
<body data-mode="both">
  <a class="skip" href="#main">Skip to reading</a>
  <button type="button" class="nav-toggle" id="nav-toggle" aria-expanded="false" aria-controls="chapter-side">
    Chapters
  </button>
  <div class="nav-backdrop" id="nav-backdrop" hidden></div>
  <aside class="side" id="chapter-side" aria-label="Chapter navigation">
    <button type="button" class="nav-close" id="nav-close" aria-label="Close chapters">×</button>
    <div class="side-head">
      <div class="brand"><a href="../../index.html">grimoire · smut</a></div>
      <h1>{html.escape(title)}</h1>
      <p class="sub">{sub_html}</p>
      {epigraph_html}
      <div class="stats">
        <div><strong>{len(chapters)}</strong> chapter{"s" if len(chapters) != 1 else ""}</div>
        <div><strong>{shadow:,}</strong> / {target:,} Book 1</div>
        <div><strong>{total_words:,}</strong> series</div>
        <div>{html.escape(now)}</div>
      </div>
      <div class="mode" role="group" aria-label="Page mode">
        <button type="button" data-mode="desk">Desk</button>
        <button type="button" data-mode="both" class="on">Both</button>
        <button type="button" data-mode="prose">Prose</button>
      </div>
      <p class="mode-hint">Desk = spine + cards. Prose = the book. Both = how we edit.</p>
      <p class="spine-link"><a href="#spine">Spine ↓</a></p>
    </div>
    <nav class="nav" aria-label="Chapters">
      {"".join(nav)}
    </nav>
  </aside>
  <div class="shell">
    <div class="side-spacer" aria-hidden="true"></div>
    <main class="main" id="main">
      <header class="hero">
        <div class="badge">{html.escape(badge)}</div>
        <h1>{html.escape(title)}</h1>
        <p>{html.escape(hero_line)}</p>
      </header>
      {spine_html(chapters)}
      {"".join(sections)}
      <footer class="foot">
        {html.escape(title)} · {html.escape(author)} · {html.escape(status)} · not on GitHub.
        Desk cards live in chapter front matter.
      </footer>
    </main>
  </div>
  <a class="top" href="#">Top</a>
</body>
</html>
"""
    OUT.write_text(page, encoding="utf-8")
    print(f"Wrote {OUT}")
    print(f"Chapters: {len(chapters)}")
    print(f"Book 1: {shadow:,} / {target:,}")
    print(f"Series: {total_words:,} / 400–450k")
    return OUT


if __name__ == "__main__":
    build()
