"""Dump folder → audit → apply → build → git commit → push.

  python scripts/drop_in.py
  python scripts/drop_in.py "C:\\Users\\MichaelThomson\\Downloads\\edits-pass3"
  python scripts/drop_in.py --list
  python scripts/drop_in.py --no-push
  python scripts/drop_in.py --no-git

Naming law: docs/SCRIPTS.md

Chapters:  ch-04-joss.txt
Plan:      plan-outline.txt  /  outline.txt  /  09-protagonist.txt
Notes:     README / HOW-TO / THIS-PASS / CARD-PATCHES — skipped, reported.

Unknown names and missing destinations are ERRORs. A chapter or plan page
that comes in at less than half the on-disk word count is an ERROR (regression).
Less than 80% is a WARN. --allow-shrink if Master meant a cut.
The run stops before writing if any ERROR is found.
Doubled (1) copies apply oldest → newest.
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CHAPTERS = ROOT / "chapters"
DOCS = ROOT / "docs"
DEFAULT_IN = Path.home() / "Downloads" / "edits"
SMUT = ROOT.parent.parent  # books/seven-year-king → books → smut

QUOTE_MAP = str.maketrans(
    {
        "\u2018": "'",
        "\u2019": "'",
        "\u201d": '"',
        "\u201c": '"',
        "\u2013": "—",
        "\u00a0": " ",
    }
)

COPY_RE = re.compile(r"\s*\(\d+\)\s*$")
CH_PREFIX_RE = re.compile(r"^ch-(\d{1,2})(?:[-_.]|$)", re.I)
PLAN_PREFIX_RE = re.compile(r"^(?:plan|doc|docs)[-_]", re.I)
NUM_RE = re.compile(r"^(\d{1,2})([-_.]|$)")
HEADING_RE = re.compile(r"^\d{1,2}\s*[·.\-–—]\s+\S")
PAREN_NOTE_RE = re.compile(r"^\([^)]+\)\s*$")
SKIP_DOCS = {"wordcount.md"}
SKIP_STEM = re.compile(r"readme|how-to|card-patches|this-pack|this-pass", re.I)
SHRINK_ERROR = 0.50
SHRINK_WARN = 0.80
GROW_WARN = 4.0
MIN_COMPARE_CHAPTER = 80
MIN_COMPARE_PLAN = 50


@dataclass
class Verdict:
    status: str  # ok | skip | error
    kind: str
    src: Path
    dest: Path | None
    detail: str


def write_if_changed(path: Path, text: str) -> bool:
    if not text.endswith("\n"):
        text += "\n"
    new = text.replace("\r\n", "\n").encode("utf-8")
    if path.exists():
        old = path.read_bytes().replace(b"\r\n", b"\n").replace(b"\r", b"\n")
        if old == new:
            return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(new)
    return True


def stem_key(name: str) -> str:
    return COPY_RE.sub("", Path(name).stem).strip()


def git_root() -> Path:
    p = ROOT
    for q in [p, *p.parents]:
        if (q / ".git").exists():
            return q
    raise SystemExit("ERROR: not inside a git repo (looked from books/seven-year-king upward)")


def docs_index() -> dict[str, Path]:
    idx: dict[str, Path] = {}
    for p in DOCS.glob("*.md"):
        idx[p.name.lower()] = p
        idx[p.stem.lower()] = p
        idx[p.stem.lower().replace("_", "-")] = p
    return idx


def match_doc(stem: str, idx: dict[str, Path]) -> Path | None:
    raw = PLAN_PREFIX_RE.sub("", stem).strip("-_ ")
    key = raw.lower().replace("_", "-")
    if key + ".md" in idx:
        return idx[key + ".md"]
    if key in idx:
        return idx[key]
    hits = [
        p
        for k, p in idx.items()
        if not k.endswith(".md")
        and (k == key or k.endswith("-" + key) or k.endswith("_" + key))
    ]
    uniq = {p.resolve(): p for p in hits}
    if len(uniq) == 1:
        return next(iter(uniq.values()))
    return None


def chapter_for(num: int) -> Path | None:
    hits = sorted(CHAPTERS.rglob(f"ch-{num:02d}-*.md"))
    if not hits:
        hits = sorted(CHAPTERS.rglob(f"ch-{num}-*.md"))
    return hits[0] if hits else None


def known_chapter_nums() -> set[int]:
    nums: set[int] = set()
    for p in CHAPTERS.rglob("ch-*.md"):
        m = re.search(r"ch-(\d+)", p.name, re.I)
        if m:
            nums.add(int(m.group(1)))
    return nums


def classify(path: Path, idx: dict[str, Path]) -> Verdict:
    stem = stem_key(path.name)
    parent = path.parent.name.lower()
    rel_parts = {p.lower() for p in path.parts}

    if SKIP_STEM.search(stem):
        return Verdict("skip", "notes", path, None, "notes file (README / HOW-TO / THIS-PASS / CARD-PATCHES)")

    if path.name.lower() in SKIP_DOCS or stem.lower() == "wordcount":
        return Verdict(
            "error",
            "plan",
            path,
            None,
            "WORDCOUNT.md is generated by build.py — do not drop it in",
        )

    def as_chapter(num: int, rest: str = "") -> Verdict:
        dest = chapter_for(num)
        if dest is None:
            known = ", ".join(f"{n:02d}" for n in sorted(known_chapter_nums())) or "(none)"
            return Verdict(
                "error",
                "chapter",
                path,
                None,
                f"no chapter {num:02d} on disk. Living numbers: {known}. "
                f"Name it ch-NN-slug.txt to match chapters/**/ch-NN-*.md",
            )
        if rest:
            dest_rest = re.sub(r"^ch-\d{1,2}-?", "", dest.stem, flags=re.I).lower()
            rest_n = rest.lower().replace("_", "-")
            if dest_rest and rest_n and rest_n not in dest_rest and dest_rest not in rest_n:
                # ch-06-the-candle → ch-06-kettles.md is allowed (living title vs filename)
                if not CH_PREFIX_RE.match(stem):
                    return Verdict(
                        "error",
                        "chapter",
                        path,
                        dest,
                        f"slug '{rest}' does not match {dest.name}. "
                        f"If this is chapter {num:02d}, name it {dest.name.replace('.md', '.txt')} "
                        f"or ch-{num:02d}-….txt. If this is notes, do not start with {num:02d}-",
                    )
        return Verdict("ok", "chapter", path, dest, "")

    def as_plan() -> Verdict:
        dest = match_doc(stem, idx)
        if dest is None:
            return Verdict(
                "error",
                "plan",
                path,
                None,
                f"no docs page for '{stem}'. Use plan-<stem>.txt matching a file in docs/ "
                f"(plan-outline.txt, plan-tracker.txt, 09-protagonist.txt).",
            )
        if dest.name.lower() in SKIP_DOCS:
            return Verdict("error", "plan", path, dest, "WORDCOUNT.md is generated — do not drop it")
        return Verdict("ok", "plan", path, dest, "")

    if parent in {"chapters", "chapter"} or "chapters" in rel_parts:
        m = CH_PREFIX_RE.match(stem) or NUM_RE.match(stem)
        if not m:
            return Verdict(
                "error",
                "chapter",
                path,
                None,
                "in a chapters/ folder but name is not ch-NN-… or NN-…",
            )
        rest = CH_PREFIX_RE.sub("", stem) if CH_PREFIX_RE.match(stem) else NUM_RE.sub("", stem)
        return as_chapter(int(m.group(1)), rest.strip("-_."))

    if parent in {"docs", "plan", "planning"}:
        return as_plan()

    if CH_PREFIX_RE.match(stem):
        m = CH_PREFIX_RE.match(stem)
        rest = CH_PREFIX_RE.sub("", stem).strip("-_.")
        return as_chapter(int(m.group(1)), rest)

    if PLAN_PREFIX_RE.match(stem):
        return as_plan()

    dest = match_doc(stem, idx)
    if dest is not None:
        return Verdict("ok", "plan", path, dest, "")

    m = NUM_RE.match(stem)
    if m:
        rest = NUM_RE.sub("", stem).strip("-_.")
        return as_chapter(int(m.group(1)), rest)

    return Verdict(
        "error",
        "unknown",
        path,
        None,
        "name not recognised. Chapters: ch-04-joss.txt  Plan: plan-outline.txt  "
        "Notes: README-….txt (skipped). See docs/SCRIPTS.md",
    )


def iter_dropins(folder: Path) -> list[Path]:
    files: list[Path] = []
    for p in folder.rglob("*"):
        if not p.is_file() or p.name.startswith("."):
            continue
        if p.suffix.lower() not in {".txt", ".md"}:
            continue
        files.append(p)
    return files


def audit(folder: Path, allow_shrink: bool = False) -> list[Verdict]:
    idx = docs_index()
    out: list[Verdict] = []
    for src in sorted(iter_dropins(folder), key=lambda p: p.name.lower()):
        v = classify(src, idx)
        if v.status == "ok" and v.dest is not None:
            try:
                text = src.read_text(encoding="utf-8")
            except OSError as e:
                out.append(Verdict("error", v.kind, src, v.dest, f"cannot read: {e}"))
                continue
            words = len(text.split())
            if words == 0:
                out.append(Verdict("error", v.kind, src, v.dest, "file is empty"))
                continue
            if v.kind == "chapter" and text.lstrip().startswith("---"):
                v = Verdict(
                    "error",
                    v.kind,
                    src,
                    v.dest,
                    "starts with YAML --- ; chapter drop-ins must be prose only "
                    "(the desk card on disk is kept)",
                )
            elif words < 30:
                v = Verdict(
                    "ok",
                    v.kind,
                    src,
                    v.dest,
                    f"WARN short ({words} words) — check this is not a stub or a notes leak",
                )
        out.append(v)
    return apply_size_bounds(out, allow_shrink=allow_shrink)


def disk_prose_words(path: Path, kind: str) -> int:
    raw = path.read_text(encoding="utf-8")
    if kind == "chapter":
        _yaml, body = split_front_matter(raw)
        _k, _t, prose = split_headings(body)
        return len(prose.split())
    return len(raw.split())


def incoming_prose_words(src: Path, kind: str, dest_name: str) -> int:
    raw = src.read_text(encoding="utf-8")
    if kind == "chapter":
        prose = clean_chapter(raw)
        _k, _t, rest = split_headings(prose)
        text = rest if rest.strip() else prose
        return len(text.split())
    return len(clean_plan(raw, dest_name).split())


def apply_size_bounds(verdicts: list[Verdict], allow_shrink: bool = False) -> list[Verdict]:
    """Newest copy per dest vs on-disk prose. Catch AI cutting a room in half."""
    by_dest: dict[Path, list[int]] = {}
    for i, v in enumerate(verdicts):
        if v.status == "ok" and v.dest is not None:
            by_dest.setdefault(v.dest, []).append(i)
    for dest, idxs in by_dest.items():
        idxs.sort(key=lambda i: (verdicts[i].src.stat().st_mtime, verdicts[i].src.name))
        last = idxs[-1]
        v = verdicts[last]
        if not dest.exists():
            continue
        old_n = disk_prose_words(dest, v.kind)
        floor = MIN_COMPARE_CHAPTER if v.kind == "chapter" else MIN_COMPARE_PLAN
        if old_n < floor:
            continue
        new_n = incoming_prose_words(v.src, v.kind, dest.name)
        ratio = new_n / old_n if old_n else 1.0
        extra = v.detail
        if ratio < SHRINK_ERROR:
            msg = (
                f"regression: {new_n} words incoming vs {old_n} on disk "
                f"({ratio:.0%}). Drop-ins must not cut a {'chapter' if v.kind == 'chapter' else 'plan page'} "
                f"in half. Use --allow-shrink if Master meant a cut."
            )
            if allow_shrink:
                verdicts[last] = Verdict("ok", v.kind, v.src, v.dest, "WARN " + msg)
            else:
                verdicts[last] = Verdict("error", v.kind, v.src, v.dest, msg)
        elif ratio < SHRINK_WARN:
            note = f"WARN shrink {new_n} vs {old_n} on disk ({ratio:.0%})"
            verdicts[last] = Verdict("ok", v.kind, v.src, v.dest, (extra + "; " if extra else "") + note)
        elif ratio > GROW_WARN:
            note = f"WARN grew {new_n} vs {old_n} on disk ({ratio:.0%}) — check this is flesh not a paste dump"
            verdicts[last] = Verdict("ok", v.kind, v.src, v.dest, (extra + "; " if extra else "") + note)
    return verdicts


def pick_jobs(verdicts: list[Verdict]) -> dict[Path, list[tuple[str, Path]]]:
    buckets: dict[Path, list[tuple[str, Path, float]]] = {}
    for v in verdicts:
        if v.status != "ok" or v.dest is None:
            continue
        buckets.setdefault(v.dest, []).append((v.kind, v.src, v.src.stat().st_mtime))
    out: dict[Path, list[tuple[str, Path]]] = {}
    for dest, items in buckets.items():
        items.sort(key=lambda t: (t[2], t[1].name))
        out[dest] = [(k, s) for k, s, _ in items]
    return out


def split_front_matter(raw: str) -> tuple[str, str]:
    if not raw.startswith("---"):
        return "", raw
    rest = raw[3:].lstrip("\n")
    end = rest.find("\n---")
    if end < 0:
        return "", raw
    yaml = rest[:end].rstrip() + "\n"
    body = rest[end + 4 :].lstrip("\n")
    return yaml, body


def split_headings(body: str) -> tuple[str, str, str]:
    lines = body.splitlines()
    kicker = ""
    title = ""
    i = 0
    if i < len(lines) and lines[i].startswith("# "):
        kicker = lines[i]
        i += 1
    if i < len(lines) and lines[i].startswith("## "):
        title = lines[i]
        i += 1
    while i < len(lines) and not lines[i].strip():
        i += 1
    return kicker, title, "\n".join(lines[i:]).strip() + "\n"


def clean_chapter(text: str) -> str:
    text = text.translate(QUOTE_MAP).replace("\r\n", "\n").replace("\r", "\n")
    lines = text.splitlines()
    i = 0
    if i < len(lines) and HEADING_RE.match(lines[i].strip()):
        i += 1
        if i < len(lines) and PAREN_NOTE_RE.match(lines[i].strip()):
            i += 1
        while i < len(lines) and not lines[i].strip():
            i += 1
    return "\n".join(lines[i:]).strip() + "\n"


def clean_plan(text: str, dest_name: str) -> str:
    text = text.translate(QUOTE_MAP).replace("\r\n", "\n").replace("\r", "\n")
    lines = text.splitlines()
    if lines:
        first = lines[0].strip().strip("`").replace("\\", "/")
        if first.lower() in {
            dest_name.lower(),
            "docs/" + dest_name.lower(),
            dest_name.lower().replace(".md", ".txt"),
        }:
            lines = lines[1:]
            while lines and not lines[0].strip():
                lines = lines[1:]
    return "\n".join(lines).strip() + "\n"


def stamp_notes(yaml: str, src_name: str) -> str:
    line = f"  Drop-in: {src_name} ({datetime.now().strftime('%Y-%m-%d')})."
    if "Drop-in:" in yaml:
        return re.sub(r"  Drop-in:.*", line, yaml, count=1)
    if re.search(r"^notes:\s*\|", yaml, re.M) or re.search(r"^notes:", yaml, re.M):
        return yaml.rstrip() + "\n" + line + "\n"
    return yaml.rstrip() + "\nnotes: |\n" + line + "\n"


def install_chapter(src: Path, dest: Path) -> str:
    yaml, old_body = split_front_matter(dest.read_text(encoding="utf-8"))
    kicker, title, _old = split_headings(old_body)
    prose = clean_chapter(src.read_text(encoding="utf-8"))
    dk, dt, rest = split_headings(prose)
    if dk or dt:
        kicker = dk or kicker
        title = dt or title
        prose = rest
    yaml = stamp_notes(yaml, src.name)
    parts = ["---\n", yaml]
    if not yaml.endswith("\n"):
        parts.append("\n")
    parts.append("---\n\n")
    if kicker:
        parts.append(kicker + "\n")
    if title:
        parts.append(title + "\n")
    parts.append("\n")
    parts.append(prose if prose.endswith("\n") else prose + "\n")
    changed = write_if_changed(dest, "".join(parts))
    words = len(prose.split())
    tag = "OK  " if changed else "same"
    return f"{tag} {src.name} → {dest.relative_to(ROOT)} ({words} words)"


def install_plan(src: Path, dest: Path) -> str:
    body = clean_plan(src.read_text(encoding="utf-8"), dest.name)
    changed = write_if_changed(dest, body)
    words = len(body.split())
    tag = "OK  " if changed else "same"
    return f"{tag} {src.name} → {dest.relative_to(ROOT)} ({words} words)"


def print_audit(verdicts: list[Verdict], jobs: dict[Path, list[tuple[str, Path]]]) -> int:
    errors = 0
    for v in verdicts:
        name = v.src.name
        if v.status == "error":
            errors += 1
            print(f"ERROR  {name}")
            print(f"       {v.detail}")
            continue
        if v.status == "skip":
            print(f"SKIP   {name}  — {v.detail}")
            continue
        dest = v.dest.relative_to(ROOT) if v.dest else "?"
        extra = f"  ({v.detail})" if v.detail else ""
        chain = jobs.get(v.dest or Path(), [])
        later = ""
        if v.dest and len(chain) > 1 and chain[-1][1] != v.src:
            later = "  (then newer copy)"
        print(f"OK     {v.kind:7} {name} → {dest}{later}{extra}")
    if not verdicts:
        print("ERROR  folder has no .txt / .md files")
        return 1
    oks = sum(1 for v in verdicts if v.status == "ok")
    skips = sum(1 for v in verdicts if v.status == "skip")
    print(f"— {oks} ok, {skips} skipped, {errors} error(s)")
    return errors


def git_cmd(repo: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", "-C", str(repo), *args],
        capture_output=True,
        text=True,
        encoding="utf-8",
    )


def publish(folder: Path, do_push: bool) -> int:
    repo = git_root()
    rel = ROOT.relative_to(repo).as_posix()
    add = git_cmd(repo, "add", rel)
    if add.returncode != 0:
        print(f"ERROR  git add failed:\n{add.stderr or add.stdout}")
        return 1
    st = git_cmd(repo, "status", "--porcelain", "--", rel)
    if not (st.stdout or "").strip():
        print("git: nothing to commit (working tree clean for this book)")
        return 0
    label = folder.name
    msg = f"Drop-in {label}."
    commit = git_cmd(repo, "commit", "-m", msg)
    if commit.returncode != 0:
        print(f"ERROR  git commit failed:\n{commit.stderr or commit.stdout}")
        return 1
    log = git_cmd(repo, "log", "-1", "--oneline")
    print(f"git: {(log.stdout or '').strip()}")
    if not do_push:
        print("git: not pushed (--no-push)")
        return 0
    push = git_cmd(repo, "push", "origin", "HEAD")
    if push.returncode != 0:
        print(f"ERROR  git push failed:\n{push.stderr or push.stdout}")
        print("       commit is local. Fix auth and push, or say so — do not pretend it published.")
        return 1
    print("git: pushed")
    return 0


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "folder",
        nargs="?",
        default=str(DEFAULT_IN),
        help="Folder of drop-ins (default: ~/Downloads/edits)",
    )
    p.add_argument("--list", action="store_true", help="Audit only: mapping + errors, write nothing")
    p.add_argument("--no-build", action="store_true", help="Do not run scripts/build.py")
    p.add_argument("--no-git", action="store_true", help="Do not commit or push")
    p.add_argument("--no-push", action="store_true", help="Commit locally, do not push")
    p.add_argument(
        "--allow-shrink",
        action="store_true",
        help="Do not ERROR when a drop-in is under half the on-disk word count",
    )
    args = p.parse_args()
    folder = Path(args.folder)
    if not folder.is_dir():
        raise SystemExit(f"ERROR: not a folder: {folder}")

    verdicts = audit(folder, allow_shrink=args.allow_shrink)
    jobs = pick_jobs(verdicts)
    nerr = print_audit(verdicts, jobs)
    if nerr:
        raise SystemExit(
            f"ERROR: {nerr} bad file(s). Fix names and re-run. Nothing was written."
        )
    if not jobs:
        raise SystemExit("ERROR: nothing to apply (only notes, or empty folder).")
    if args.list:
        return

    for dest in sorted(jobs, key=lambda q: str(q).lower()):
        chain = jobs[dest]
        for i, (kind, src) in enumerate(chain):
            note = "" if i == len(chain) - 1 else "  (then newer copy)"
            if kind == "chapter":
                print(install_chapter(src, dest) + note)
            else:
                print(install_plan(src, dest) + note)

    if not args.no_build:
        print("— build —")
        r = subprocess.run(
            [sys.executable, str(ROOT / "scripts" / "build.py")],
            cwd=ROOT,
        )
        if r.returncode != 0:
            raise SystemExit("ERROR: build.py failed. Files are on disk. Git not run.")

    if not args.no_git:
        print("— git —")
        code = publish(folder, do_push=not args.no_push)
        if code:
            raise SystemExit(code)


if __name__ == "__main__":
    main()
